export type StackParamList = {
    Welcome: undefined;
    SignIn: undefined;
    SignUp: undefined;
    ForgotPassword: undefined;
    ResetPassword: undefined;
    CustomDrawer: undefined;
    Home: undefined;
    Setting: undefined;
    CustomBottomTabNavigator: undefined;
    Wallet: undefined;
    Bank: undefined;
    Ewallet: undefined;
    Expenses: undefined;
    Language: undefined;
    UserEdit: undefined;
    WalletIncome: undefined;
    WalletSpend: undefined;
    EWalletIncome: undefined;
    EWalletSpend: undefined;
    BankDetail: undefined;
    BankIncome: undefined;
    BankSpend: undefined;
    ThemeChange: undefined;
    Verify: { length: number; value: string[]; disabled: boolean; onChange: (value: string[]) => void };
    ResetVerify: { length: number; value: string[]; disabled: boolean; onChange: (value: string[]) => void };
    UserEditVerify: { length: number; value: string[]; disabled: boolean; onChange: (value: string[]) => void };
};
